name: Build APK
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      
      - name: Setup Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: 3.13

      - name: Setup Java JDK
        uses: actions/setup-java@v6.0.1
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3.2.1
        with:
          # cmdline-tools-version: 14742923
          # cmdline-tools-version. See https://developer.android.com/studio#command-line-tools-only
          # Android SDK is usable only after the license agreement. Should setup-android agree to the licences, provided by "sdkmanager --licenses"
          accept-android-sdk-licenses: true
          # Should accepted licenses be logged. If not, accepted licences will be acce  pted silently
          log-accepted-android-sdk-licenses: true
          packages: 'platform-tools cmdline-tools;latest build-tools;34.0.0'

      - name: Flutter action
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: '3.44.8'
          channel: 'stable'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip || python3 -m pip install --upgrade pip
          pip install flet pymupdf
          
      - name: Fix JNI dependency
        run: |
          flutter pub add jni:^1.1.0
          flutter pub get

      - name: Build Flet APK
        run: flet build apk o_leitor/ -v
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.2
        with:
          name: o-leitor-apk
          path: o_leitor/build/apk/*.apk
          if-no-files-found: error
          
